# /etc/nixos/configuration.nix
{ config, lib, pkgs, ... }:

let 
  vars = import ./vars.nix;
in
{
  imports = [
    ./hardware-configuration.nix  # generated by nixos-generate-config
    ./modules/base.nix
    ./modules/security-tools.nix
    ./modules/blockchain.nix
    ./modules/development.nix
    ./vars.nix
  ] ++ lib.optionals vars.enableGUI [
    ./modules/graphical.nix
  ];

  # Bootloader
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Kernel (latest for hardware support, or hardened for security)
  boot.kernelPackages = pkgs.linuxPackages_latest;

  # Hostname
  networking.hostName = vars.hostname;

  # Networking
  networking.networkmanager.enable = true;

  # Firewall
  networking.firewall = {
    enable = true;
    allowedTCPPorts = [ 22 ];
    # allowedUDPPorts = [ ];
  };

  # Timezone & locale
  time.timeZone = "Europe/Rome";  # adjust
  services.timesyncd.enable = true;
  i18n.defaultLocale = "en_US.UTF-8";
  console.keyMap = "it";

  # User account
  users.users.${vars.username} = {
    isNormalUser = true;
    extraGroups = [ 
      "wheel" 
      "networkmanager" 
      "docker" 
      "libvirtd" 
      "wireshark"
      "audio"
      "video"
      "input"
      "tty"
    ];
    shell = pkgs.zsh;
    openssh.authorizedKeys.keys = [ "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJckU1t8cST9dh+tVoQT5SzahGOKjzmPzL4gtZHE3QQsWBtpV34ic7UMKnUal9Apiltw5eAe3N/5oqy5uT3yB9UhAMETLdh2eKes9dFhDi5FCwAriqPcpCSyOYp1AXMwA1Ok/zvpeFnJYc6sizV/rq8TLr4HATI0r5XWWQdO8HM+aXLh/+d64UnQFLrzmcpGhnKvxBl96F8nfRpsTM+UMt0zGExS9PNIkVKcCXX+7/SfmHE4vOUmD7X4Vn5NqggpBobI5a2Omi1N/dPFUBxBkHk/wZKxt4PXzYtldrW0pBpd0nroUraumqxPAtjAegyVUhNCN3XkdVj2L/cuYxfrwibOJG18djDa1X8HPq5o8y8QZhY7ZbT4nQv9D2h3WnHeunkkP3GqlDaGV3/f9e65C1AqwzTwMD09zRqOfvNx6emT1bRiHwo7GQ6enQq3tqbMJ7/NpnJJ4bHam++RaaP6AL5mnqnKWYVNyhDlw1k9y3vSob0G5dyE4FeXYduLD0PZk=" ];  # for remote
  };

  # Enable nix-ld for running unpatched binaries (Binary Ninja, etc.)
  programs.nix-ld = {
    enable = true;
    libraries = with pkgs; [
      stdenv.cc.cc
      zlib
      openssl
      curl
      libGL
      libGLU
      xorg.libX11
      xorg.libXcursor
      xorg.libXrandr
      xorg.libXi
      xorg.libXext
      xorg.libXrender
      xorg.libXfixes
      fontconfig
      freetype
      gtk3
      glib
      dbus
      nss
      nspr
      atk
      cups
      libdrm
      expat
      libxkbcommon
      alsa-lib
      pango
      cairo
    ];
  };

  # Bluetooth (conditional)
  services.blueman.enable = vars.enableBluetooth;

  # Audio
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # Docker
  virtualisation.docker = {
    enable = true;
    enableOnBoot = true;
  };

  # Libvirt/QEMU for VMs
  virtualisation.libvirtd = {
    enable = true;
    qemu = {
      package = pkgs.qemu_kvm;
    };
  };

  # SSH
  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = false;
      PermitRootLogin = "no";
    };
  };

  # Zsh
  programs.zsh = {
    enable = true;
    enableCompletion = true;
    syntaxHighlighting.enable = true;
    autosuggestions.enable = true;
  };

  # Nix settings
  nix = {
    settings = {
      experimental-features = [ "nix-command" "flakes" ];
      auto-optimise-store = true;
    };
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 14d";
    };
  };

  # Allow unfree packages (for CUDA, Binary Ninja, etc.)
  nixpkgs.config.allowUnfree = true;

  system.stateVersion = "24.11";  # Don't change after install
}

