# /etc/nixos/configuration.nix
{ config, lib, pkgs, ... }:

let
  # Toggle these per machine
  enableGUI = true;        # false for headless servers (Hetzner)
  enableBluetooth = true;  # false for servers
  hostname = "nsa-router";     # change per machine
  username = "renny";       # your username
in
{
  imports = [
    ./hardware-configuration.nix  # generated by nixos-generate-config
    ./modules/base.nix
    ./modules/security-tools.nix
    ./modules/blockchain.nix
    ./modules/development.nix
  ] ++ lib.optionals enableGUI [
    ./modules/graphical.nix
  ];

  # Bootloader
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Kernel (latest for hardware support, or hardened for security)
  boot.kernelPackages = pkgs.linuxPackages_latest;

  # Hostname
  networking.hostName = hostname;

  # Networking
  networking.networkmanager.enable = true;

  # Firewall
  networking.firewall = {
    enable = true;
    allowedTCPPorts = [ 22 ];
    # allowedUDPPorts = [ ];
  };

  # Timezone & locale
  time.timeZone = "Europe/Rome";  # adjust
  services.timesyncd.enable = true;
  i18n.defaultLocale = "en_US.UTF-8";

  # User account
  users.users.${username} = {
    isNormalUser = true;
    extraGroups = [ 
      "wheel" 
      "networkmanager" 
      "docker" 
      "libvirtd" 
      "wireshark"
      "audio"
      "video"
      "input"
      "tty"
    ];
    shell = pkgs.zsh;
    # openssh.authorizedKeys.keys = [ "ssh-ed25519 AAAA..." ];  # for remote
  };

  # Enable nix-ld for running unpatched binaries (Binary Ninja, etc.)
  programs.nix-ld = {
    enable = true;
    libraries = with pkgs; [
      stdenv.cc.cc
      zlib
      openssl
      curl
      libGL
      libGLU
      xorg.libX11
      xorg.libXcursor
      xorg.libXrandr
      xorg.libXi
      xorg.libXext
      xorg.libXrender
      xorg.libXfixes
      fontconfig
      freetype
      gtk3
      glib
      dbus
      nss
      nspr
      atk
      cups
      libdrm
      expat
      libxkbcommon
      alsa-lib
      pango
      cairo
    ];
  };

  # Bluetooth (conditional)
  services.blueman.enable = enableBluetooth;

  # Audio
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # Docker
  virtualisation.docker = {
    enable = true;
    enableOnBoot = true;
  };

  # Libvirt/QEMU for VMs
  virtualisation.libvirtd = {
    enable = true;
    qemu = {
      package = pkgs.qemu_kvm;
    };
  };

  # SSH
  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = false;
      PermitRootLogin = "no";
    };
  };

  # Zsh
  programs.zsh = {
    enable = true;
    enableCompletion = true;
    syntaxHighlighting.enable = true;
    autosuggestions.enable = true;
  };

  # Nix settings
  nix = {
    settings = {
      experimental-features = [ "nix-command" "flakes" ];
      auto-optimise-store = true;
    };
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 14d";
    };
  };

  # Allow unfree packages (for CUDA, Binary Ninja, etc.)
  nixpkgs.config.allowUnfree = true;

  system.stateVersion = "24.11";  # Don't change after install
}
